### PR TITLE
MacOS support

### PR DESCRIPTION
**Pull request by ajbdev**
Just copied in libsdl from brew and it appeared to work out of the box. All the examples loaded.

Screenshot 2023-04-11 at 9 23 14 PM

Tests also passed:

```
andy@Andys-MacBook-Pro-2 SDL_ts % deno task test                                                                                                           (git)-[macos-support] 
Task test deno test --unstable --allow-ffi
Check file:///Users/andy/src/SDL_ts/src/boxes.test.ts
running 10 tests from ./src/boxes.test.ts
I8 can be boxed ... ok (3ms)
U8 can be boxed ... ok (4ms)
I16 can be boxed ... ok (3ms)
U16 can be boxed ... ok (3ms)
I32 can be boxed ... ok (4ms)
U32 can be boxed ... ok (3ms)
Int can be boxed ... ok (4ms)
F32 can be boxed ... ok (3ms)
F64 can be boxed ... ok (3ms)
Pointer can be boxed ... ok (4ms)

ok | 10 passed | 0 failed (50ms)
```

### CODE REVIEW

**Comment by smack0007** [comment]
Hey first off thanks for this and I'm glad that you could get it working on Mac even though you're having problems on Windows. I'm glad someone else is taking interest other than myself.

The only issue I have with the pull request is that I would actually like to move away from having the SDL binaries inside this repo. I did it for Windows as a crutch to get the project going but long term I plan to replace that with a script that will download the binaries for you. Long term it wouldn't be sustainable to have binaries in the repo for every OS / architecture.

I don't own a Mac so I'm flying completely blind here but on Linux after installing the binaries they can just be referenced by their filename. On Debian I actually change the filename for libSDL2_image.so and libSDL2_ttf.so. See here:
https://github.com/smack0007/SDL_ts/blob/SameGame/src/deno/_library.ts#L48

Can you please try that out?

**Comment by ajbdev** [comment]
The problem with mac is there isn't a straightforward installation path. You can install via brew, macports, or from source. Actually, I originally tried building from source but couldn't figure out how to produce the required .dylib files, but this is definitely due to my lack of understanding. Brew installs the actual dynlib files, but it's stored in the typical brew path (/opt/homebrew/**) which is not a typical posix location for libraries. I could certainly reference that path but that will only work if others install via brew.

**Comment by smack0007** [comment]
`getLibraryPaths` returns multiple paths where the binary should be looked for so there being multiple places to look wouldn't be a problem.

**Comment by ajbdev** [comment]
That makes sense, how's this? https://github.com/smack0007/SDL_ts/pull/2/commits/0fecd4fb65c083aa34a8090746c8c4ed144adc37

(All tests passed)

**Comment by smack0007** [comment]
Hi sorry got sick for a few days. This looks good to me now.

Suggestion:
In the Readme there is a credits section. Maybe you would like to add your information under something like "Initial MacOS Support". Let me know what you think and then after that I'll merge it.

**Comment by ajbdev** [comment]
No worries - done!

**Pull request merged**
